# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0405081af3c08a0fb1241fbe5a5d7fbefd19bf404694acc531c52542ac7333675c80e00f3f152e6539033b8aa4c98b2dcb479d519fb2953502583f25726ddf

test:
  secret_key_base: 3b53968f2bde50251a2c1fcf2a99b79ec43225cea69bc9e372822490f6033cf9c2145259847d3ba7793b8c8d686b4813a8e58b455a862b2398d8210075311352

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: fa0405081af3c08a0fb1241fbe5a5d7fbefd19bf404694acc531c52542ac7333675c80e00f3f152e6539033b8aa4c98b2dcb479d519fb2953502583f25726ddf

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
