require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NewsletterEmailsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # NewsletterEmail. As you add validations to NewsletterEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip(:email)
  }
  let(:admin) {FactoryGirl.create(:admin)}

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewsletterEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all newsletter_emails as @newsletter_emails" do
      newsletter_email = NewsletterEmail.create! valid_attributes
      get :index, {}, valid_session
      sign_in :admin
      expect(assigns(:newsletter_emails)).to eq([newsletter_email])
    end
  end

  describe "GET show" do
    it "assigns the requested newsletter_email as @newsletter_email" do
      newsletter_email = NewsletterEmail.create! valid_attributes
      get :show, {:id => newsletter_email.to_param}, valid_session
      sign_in :admin
      expect(assigns(:newsletter_email)).to eq(newsletter_email)
    end
  end

  describe "GET new" do
    it "assigns a new newsletter_email as @newsletter_email" do
      get :new, {}, valid_session
      expect(assigns(:newsletter_email)).to be_a_new(NewsletterEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested newsletter_email as @newsletter_email" do
      newsletter_email = NewsletterEmail.create! valid_attributes
      get :edit, {:id => newsletter_email.to_param}, valid_session
      sign_in :admin
      expect(assigns(:newsletter_email)).to eq(newsletter_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NewsletterEmail" do
        expect {
          post :create, {:newsletter_email => valid_attributes}, valid_session
        }.to change(NewsletterEmail, :count).by(1)
      end

      it "assigns a newly created newsletter_email as @newsletter_email" do
        post :create, {:newsletter_email => valid_attributes}, valid_session
        expect(assigns(:newsletter_email)).to be_a(NewsletterEmail)
        expect(assigns(:newsletter_email)).to be_persisted
      end

      it "redirects to the created newsletter_email" do
        post :create, {:newsletter_email => valid_attributes}, valid_session
        expect(response).to redirect_to(NewsletterEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newsletter_email as @newsletter_email" do
        post :create, {:newsletter_email => invalid_attributes}, valid_session
        expect(assigns(:newsletter_email)).to be_a_new(NewsletterEmail)
      end

      it "re-renders the 'new' template" do
        post :create, {:newsletter_email => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip(:email)
      }

      it "updates the requested newsletter_email" do
        newsletter_email = NewsletterEmail.create! valid_attributes
        sign_in :admin
        put :update, {:id => newsletter_email.to_param, :newsletter_email => new_attributes}, valid_session
        newsletter_email.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested newsletter_email as @newsletter_email" do
        newsletter_email = NewsletterEmail.create! valid_attributes
        sign_in :admin
        put :update, {:id => newsletter_email.to_param, :newsletter_email => valid_attributes}, valid_session
        expect(assigns(:newsletter_email)).to eq(newsletter_email)
      end

      it "redirects to the newsletter_email" do
        newsletter_email = NewsletterEmail.create! valid_attributes
        sign_in :admin
        put :update, {:id => newsletter_email.to_param, :newsletter_email => valid_attributes}, valid_session
        expect(response).to redirect_to(newsletter_email)
      end
    end

    describe "with invalid params" do
      it "assigns the newsletter_email as @newsletter_email" do
        newsletter_email = NewsletterEmail.create! valid_attributes
        sign_in :admin
        put :update, {:id => newsletter_email.to_param, :newsletter_email => invalid_attributes}, valid_session
        expect(assigns(:newsletter_email)).to eq(newsletter_email)
      end

      it "re-renders the 'edit' template" do
        newsletter_email = NewsletterEmail.create! valid_attributes
        sign_in :admin
        put :update, {:id => newsletter_email.to_param, :newsletter_email => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newsletter_email" do
      newsletter_email = NewsletterEmail.create! valid_attributes
      sign_in :admin
      expect {
        delete :destroy, {:id => newsletter_email.to_param}, valid_session
      }.to change(NewsletterEmail, :count).by(-1)
    end

    it "redirects to the newsletter_emails list" do
      newsletter_email = NewsletterEmail.create! valid_attributes
      sign_in :admin
      delete :destroy, {:id => newsletter_email.to_param}, valid_session
      expect(response).to redirect_to(newsletter_emails_url)
    end
  end

end
